# Project: Final Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = FinalProject.o
LINKOBJ  = FinalProject.o
LIBS     = -L"D:/Comprogramming/Dev-Cpp/MinGW64/lib" -L"D:/Comprogramming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Comprogramming/Dev-Cpp/MinGW64/include" -I"D:/Comprogramming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Comprogramming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Comprogramming/Dev-Cpp/MinGW64/include" -I"D:/Comprogramming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Comprogramming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Comprogramming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Final Project.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

FinalProject.o: FinalProject.cpp
	$(CPP) -c FinalProject.cpp -o FinalProject.o $(CXXFLAGS)
